-- GamePulse Tools v0.1.0; generated from registry
insert into public.games (id,slug,name,short_description,developer,publisher,status,release_date,steam_app_id,roblox_place_id,roblox_universe_id,platforms,official_url,theme_json,media_sources_json,priority,growth_status,discovery_source,published) values ('wardogs','wardogs','WARDOGS','Every decision has a cost. Make your next deployment count.','BULKHEAD','Team17','Release soon','2026-09-10',1867240,null,null,'{PC}','https://bulkhead.com/games/wardogs/','{"primary_color":"#ff8a42","secondary_color":"#647451","accent_color":"#ff8a42","background_color":"#090b0e","panel_color":"#12161c","gradient":"radial-gradient(ellipse at 80% 20%, #64745155, transparent 70%)","hero_overlay":"linear-gradient(90deg,#090b0e,transparent)","texture":"grid","particle_style":"ambient","font_style":"display","hud_style":"tactical"}','{"official_website":"https://bulkhead.com/games/wardogs/","steam_url":"https://store.steampowered.com/app/1867240/","official_youtube":null,"official_x":null,"official_discord":null,"press_kit_url":null,"roblox_url":null}',1,'Editorial watchlist','Official developer website',true) on conflict (id) do nothing;
insert into public.games (id,slug,name,short_description,developer,publisher,status,release_date,steam_app_id,roblox_place_id,roblox_universe_id,platforms,official_url,theme_json,media_sources_json,priority,growth_status,discovery_source,published) values ('aniimo','aniimo','Aniimo','Meet your next companions. Plan a team before the adventure begins.','Pawprint Studio','Kingsglory','Release soon','2026-09-16',null,null,null,'{PC,Console,Mobile}','https://aniimo.com/main','{"primary_color":"#7be6e0","secondary_color":"#3d62ab","accent_color":"#7be6e0","background_color":"#090b0e","panel_color":"#12161c","gradient":"radial-gradient(ellipse at 80% 20%, #3d62ab55, transparent 70%)","hero_overlay":"linear-gradient(90deg,#090b0e,transparent)","texture":"grid","particle_style":"ambient","font_style":"display","hud_style":"collection"}','{"official_website":"https://aniimo.com/main","steam_url":null,"official_youtube":null,"official_x":null,"official_discord":null,"press_kit_url":null,"roblox_url":null}',2,'Editorial watchlist','Official announcement',true) on conflict (id) do nothing;
insert into public.games (id,slug,name,short_description,developer,publisher,status,release_date,steam_app_id,roblox_place_id,roblox_universe_id,platforms,official_url,theme_json,media_sources_json,priority,growth_status,discovery_source,published) values ('agartha-mog-or-die','agartha-mog-or-die','Agartha','Set your next milestone. Turn your grind into a game plan.','See Roblox listing','See Roblox listing','On Roblox',null,null,130641102725850,10571722689,'{Roblox}','https://www.roblox.com/games/130641102725850/Agartha-Mog-or-Die','{"primary_color":"#c3f66b","secondary_color":"#467e32","accent_color":"#c3f66b","background_color":"#090b0e","panel_color":"#12161c","gradient":"radial-gradient(ellipse at 80% 20%, #467e3255, transparent 70%)","hero_overlay":"linear-gradient(90deg,#090b0e,transparent)","texture":"grid","particle_style":"ambient","font_style":"display","hud_style":"arcade"}','{"official_website":"https://www.roblox.com/games/130641102725850/Agartha-Mog-or-Die","steam_url":null,"official_youtube":null,"official_x":null,"official_discord":null,"press_kit_url":null,"roblox_url":"https://www.roblox.com/games/130641102725850/"}',3,'Editorial watchlist','Official Roblox experience',true) on conflict (id) do nothing;

insert into public.tools (id,game_id,slug,name,tool_type,short_description,status,version,is_featured,config_json,updated_at) values ('loadout','wardogs','loadout-planner','Loadout & Cash Planner','loadout','Build your kit. Balance your budget. Deploy with a plan.','published','0.1.0',true,'{"slots":["Primary weapon","Secondary","Utility","Armor","Vehicle"]}','2026-09-07') on conflict (id) do nothing;
insert into public.tools (id,game_id,slug,name,tool_type,short_description,status,version,is_featured,config_json,updated_at) values ('compare','wardogs','weapon-comparator','Weapon Comparator','comparator','Compare your weapon stats side by side, before you commit.','published','0.1.0',true,'{}','2026-09-07') on conflict (id) do nothing;
insert into public.tools (id,game_id,slug,name,tool_type,short_description,status,version,is_featured,config_json,updated_at) values ('team','aniimo','team-planner','Team Planner','team','Four slots. Endless possibilities. Pick your adventure crew.','published','0.1.0',true,'{"slots":4}','2026-09-07') on conflict (id) do nothing;
insert into public.tools (id,game_id,slug,name,tool_type,short_description,status,version,is_featured,config_json,updated_at) values ('progress','agartha-mog-or-die','progress-planner','Progress Planner','progress','Track your stats and choose your next personal milestone.','published','0.1.0',true,'{"stats":["Height","Face","Frame","Bodyfat"]}','2026-09-07') on conflict (id) do nothing;
insert into public.tools (id,game_id,slug,name,tool_type,short_description,status,version,is_featured,config_json,updated_at) values ('pass','agartha-mog-or-die','pass-calculator','Progress / Pass Calculator','pass','See what a boost could save, using your observed rates.','published','0.1.0',false,'{}','2026-09-07') on conflict (id) do nothing;

insert into public.game_media (id,game_id,type,source_type,source_owner,source_url,external_url,storage_path,rights_status,license_note,attribution_text,width,height,aspect_ratio,is_primary,display_order,verified_at,created_at,updated_at) values ('wardogs-atmosphere','wardogs','background','manual','GamePulse Tools contributors','https://github.com/JasonWaker/gamepulse-tools',null,null,'approved','Original CSS and SVG atmosphere created for this project. Not official game artwork.','Original abstract companion artwork',null,null,'16/10',true,0,'2026-09-07','2026-09-07','2026-09-07') on conflict (id) do nothing;
insert into public.game_media (id,game_id,type,source_type,source_owner,source_url,external_url,storage_path,rights_status,license_note,attribution_text,width,height,aspect_ratio,is_primary,display_order,verified_at,created_at,updated_at) values ('aniimo-atmosphere','aniimo','background','manual','GamePulse Tools contributors','https://github.com/JasonWaker/gamepulse-tools',null,null,'approved','Original CSS and SVG atmosphere created for this project. Not official game artwork.','Original abstract companion artwork',null,null,'16/10',true,1,'2026-09-07','2026-09-07','2026-09-07') on conflict (id) do nothing;
insert into public.game_media (id,game_id,type,source_type,source_owner,source_url,external_url,storage_path,rights_status,license_note,attribution_text,width,height,aspect_ratio,is_primary,display_order,verified_at,created_at,updated_at) values ('agartha-mog-or-die-atmosphere','agartha-mog-or-die','background','manual','GamePulse Tools contributors','https://github.com/JasonWaker/gamepulse-tools',null,null,'approved','Original CSS and SVG atmosphere created for this project. Not official game artwork.','Original abstract companion artwork',null,null,'16/10',true,2,'2026-09-07','2026-09-07','2026-09-07') on conflict (id) do nothing;
insert into public.game_media (id,game_id,type,source_type,source_owner,source_url,external_url,storage_path,rights_status,license_note,attribution_text,width,height,aspect_ratio,is_primary,display_order,verified_at,created_at,updated_at) values ('wardogs-official-gallery','wardogs','hero','official_site','BULKHEAD','https://bulkhead.com/games/wardogs/',null,null,'review_required','Public gallery; reuse permission has not been confirmed. No image downloaded.','© BULKHEAD',null,null,'16/10',false,0,'2026-09-07','2026-09-07','2026-09-07') on conflict (id) do nothing;
insert into public.game_media (id,game_id,type,source_type,source_owner,source_url,external_url,storage_path,rights_status,license_note,attribution_text,width,height,aspect_ratio,is_primary,display_order,verified_at,created_at,updated_at) values ('aniimo-official-gallery','aniimo','hero','official_site','Pawprint Studio / Kingsglory','https://aniimo.com/main',null,null,'review_required','Official website reference only; reuse permission pending. No image downloaded.','© respective owners',null,null,'16/10',false,1,'2026-09-07','2026-09-07','2026-09-07') on conflict (id) do nothing;

insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-1','aniimo','creatures','emberpup','Emberpup','{"index":1,"type":null,"skills":null,"description":"Emberpup is listed as No. 001 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-2','aniimo','creatures','flameruff','Flameruff','{"index":2,"type":null,"skills":null,"description":"Flameruff is listed as No. 002 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-3','aniimo','creatures','scorchhowl','Scorchhowl','{"index":3,"type":null,"skills":null,"description":"Scorchhowl is listed as No. 003 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-4','aniimo','creatures','inferlupa','Inferlupa','{"index":4,"type":null,"skills":null,"description":"Inferlupa is listed as No. 004 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-5','aniimo','creatures','celestis','Celestis','{"index":5,"type":null,"skills":null,"description":"Celestis is listed as No. 005 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-6','aniimo','creatures','stellarys','Stellarys','{"index":6,"type":null,"skills":null,"description":"Stellarys is listed as No. 006 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-7','aniimo','creatures','chirpi','Chirpi','{"index":7,"type":null,"skills":null,"description":"Chirpi is listed as No. 007 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
insert into public.game_entities (id,game_id,entity_type,slug,name,data_json,source_url,verified_at,game_version,published,content_complete) values ('aniimo-8','aniimo','creatures','tromber','Tromber','{"index":8,"type":null,"skills":null,"description":"Tromber is listed as No. 008 in the official Aniimo index. Add this companion to your planning roster. Combat details are awaiting verification."}','https://wiki.aniimo.com/','2026-09-07','Official pre-release index',true,false) on conflict (id) do nothing;
